[build-system]
requires = ["setuptools>=61.0"]  # using familiar setuptools for initial release due to time constraints
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["superduperdb"]

[project]
name = "superduperdb"
version = "0.0.4"
description = "🔮 Super-power your database with AI 🔮"
readme = "README.md"
license = {file = "LICENSE"}
maintainers = [{name = "Duncan Blythe", email = "opensource@superduperdb.com"}]
classifiers = [
    "Development Status :: 1 - Planning",  # TO BE UPDATED BEFORE RELEASE
    "License :: OSI Approved :: Apple Public Source License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Typing :: Typed"  # TO BE CONFIRMED BEFORE RELEASE
]
requires-python = ">=3.8"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.in"] }

[project.optional-dependencies]
tests = ["httpx>=0.24.1", "impall>=1.2.0", "lorem>=0.1.1", "pytest>=7.3.1", "tenacity>=8.1.0"]
lint = ["black>=23.3.0", "ruff>=0.0.267"]
typing = ["mypy>=1.3.0", "boto3-stubs>=1.26.154", "types-pillow>=9.5.0.4", "types-requests>=2.31.0.1", "types-tqdm>=4.65.0.1"]
dev = ["superduperdb[tests, lint, typing]"]
docs = [
    "sphinx",
    "nbsphinx",
    "sphinx_rtd_theme",
    "pandoc",
    "ipython",
    "myst_parser",
]

[project.urls]
homepage = "https://www.superduperdb.com/"
documentation = "https://www.superduperdb.com/"  # TO BE UPDATED BEFORE RELEASE
source = "https://www.superduperdb.com/"  # TO BE UPDATED BEFORE RELEASE

[tool.black]
skip-string-normalization = true
target-version = ["py38"]

