[tool.black]
skip-string-normalization = true
target-version = ['py38']

[tool.poetry]
name = "superduperdb"
version = "0.0.3dev2"
description = "🔮 Super-power your database with AI 🔮"
authors = ["Duncan Blythe <opensource@superduperdb.com>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"

boto3 = ">=1.10"
dask = {extras = ["distributed"], version = "*"}
dill = "*"
faiss-cpu = ">=1"
fastapi = {version = "*", extras = ["all"]}
fil = ">=1.2"
flask = ">=2"
flask-cors = ">=2"
flask-httpauth = ">=4"
grpcio = "<=1.49.1"  # pymilvus and ray are contributing to the version ambiguity
ipykernel = ">=6"
lancedb = ">=0.1"
langchain = "*"
lightning = ">=2"
matplotlib = ">=3"
networkx = ">=2"
numpy = ">=1"
openai = "*"
overrides = ">=6"
pandas = ">=2"
pillow = "*"
pydantic = "*"
pymilvus = ">=1"
pymongo = ">=3"
pytorch-lightning = ">=1"
ray = ">=2"
readerwriterlock = ">=1"
requests = ">=2"
scikit-learn = ">=1"
sentence-transformers = ">=2"
sympy = ">=1"
torch = ">=2"
tqdm = ">=4"
transformers = ">=3"
typer = ">=0.7"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"


[tool.poetry.group.dev.dependencies]
black = "*"
coverage = "*"
impall = "*"
lorem = "*"
mypy = "*"
pytest = "*"
ruff = "*"
tenacity = "*"
pandoc = "*"
sphinx-rtd-theme = "*"
nbsphinx = "*"
httpx = "*"
types-requests = "*"
boto3-stubs = "*"
types-tqdm = "*"
types-pillow = "*"
pytest-annotate = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
