name: Validate code changes

on:  # rules for when this action will be triggered
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
      - ".github"
  workflow_dispatch:  # allows triggering a GitHub action manually - see 'Actions' tab

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  #---------------------------------------------------
  # Linting and Testing
  #---------------------------------------------------
  lint-type-check-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]  # TODO: add "windows-latest", "macos-latest" when Docker removed
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          # https://blog.allenai.org/python-caching-in-github-actions-e9452698e98d
          path: |
            ./.mypy_cache
            ${{ env.pythonLocation }}
          key: ${{ matrix.os }}_${{ matrix.python-version }}_${{ hashFiles('**/pyproject.toml') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install .

      - name: Check core imports
        run: |
          # This job checks that no optional dependencies are imported in the core code.
          python -m pip install impall==1.3.1
          python -m impall --NO_CLEAR_SYS_MODULES -E 'test**:superduperdb/ext**'

      - name: Basic health check
        run: |
          black --version
          ruff --version
          mypy --version

      - name: Lint and type-check
        run: |
          make lint-and-type-check

      - name: test
        run: |
          make test PYTEST_ARGUMENTS="--cov=superduperdb --cov-report=xml test"

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          env_vars: RUNNER_OS,PYTHON_VERSION
          file: ./coverage.xml
          fail_ci_if_error: false
          name: codecov-umbrella
