name: Code Testing

on:  # rules for when this action will be triggered
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
      - ".github"
  workflow_dispatch:  # allows triggering a GitHub action manually - see 'Actions' tab

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]  # TODO: add "windows-latest", "macos-latest" when Docker removed
        python-version: ["3.11"] # Due to cache limitations, check only the earliest and the latest.

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Enable Debug Output
        run: |
          echo ::set-env name=ACTIONS_STEP_DEBUG::true

      - name: Debug Hash Files
        run: |
          ls -lahR $RUNNER_TOOL_CACHE/
      
      - name: Check Hash Values
        run: |
          echo "Hash of somefile.txt: $(sha256sum pyproject.toml)"
      
      - name: Check Cache Key
        run: |
          echo "Cache Key: ${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}"
      
      #---------------------------------------------------
      # Configuring Python environments.
      #
      # We intentionally commented the `cache` field to remind us not to enable it.
      # The reason is that most of the time is spent on package installation rather than package downloading.
      # As a result, in the next step, we will cache the complete Python environment, including all pre-installed components.
      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          #cache: 'pip' # Do not activate

      - name: Cache Python ${{ matrix.python-version }}
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ matrix.os }}_python-${{ matrix.python-version }}_${{ hashFiles('**/pyproject.toml') }}
      #---------------------------------------------------

      - name: Install Dependencies
        run: python -m pip install --upgrade .[quality,testing]

      - name: Lint and type-check
        run: |
          sha256sum pyproject.toml
          cat pyproject.toml

          make lint-and-type-check
