name: Code Testing

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
      - ".github"
  workflow_dispatch:


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ---------------------------------
  # Unit Testing
  # ---------------------------------
  unit-testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: ["3.10", "3.11"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

      # Remind users to update changelog
    - name: Check Changelog Action
      uses: tarides/changelog-check-action@v2
      with:
        changelog: CHANGELOG.md

    #---------------------------------------------------
    # Configuring Python environments.
    #
    # We intentionally commented the `cache` field to remind us not to enable it.
    # The reason is that most of the time is spent on package installation rather than package downloading.
    # As a result, in the next step, we will cache the complete Python environment, including all pre-installed components.
    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Python ${{ matrix.python-version }}
      uses: actions/cache@v3
      with:
        #path: ${{ env.PIP_CACHE_DIR }} # # Cache the pip cache dir.  You still need to install the packages.
        path: ${{ env.pythonLocation }} # Cache the whole python installation dir.
        key: ${{ matrix.os }}_python-${{ matrix.python-version }}_${{ hashFiles('pyproject.toml', '*/pyproject.toml') }}

    - name: Check core imports
      run: |
        python -m pip install impall==1.3.1
        python -m impall --NO_CLEAR_SYS_MODULES -E 'test**:superduperdb/ext**'

    - name: Lint and type-check
      run: |
        make lint-and-type-check

    - name: Unit Testing
      run: |
        make unit-testing PYTEST_ARGUMENTS="--cov=superduperdb --cov-report=xml"
        

  # ---------------------------------
  # Integration Testing
  # ---------------------------------
  integration-testing:
    needs: [ 'unit-testing' ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Docker Cache Storage Backend
      run: |
        docker buildx create --use --driver=docker-container        

    - name: Build Sandbox Image
      run: |
        # Build sandbox image for testing.
        make testenv_image EXTRA_ARGS="--cache-to type=gha --cache-from type=gha"

    - name: Start Testing Environment
      run: |
        # Update hostnames
        echo  127.0.0.1 mongodb | sudo tee -a /etc/hosts
        
        # Run the integrated testing environment
        make testenv_init

    - name: Integration Testing
      run: |
        # Run the test-suite within the sandbox image.
        docker run --entrypoint '/bin/sh' superduperdb/sandbox:latest -c 'make integration-testing PYTEST_ARGUMENTS="--cov=superduperdb --cov-report=xml"'

    - name: Shutdown Testing Environment
      run: |
        # Run the integrated testing environment
        make testenv_init

        # Remove the data directory
        sudo rm -rf deploy/testenv/.test_data     
    

    #      - name: Upload code coverage to Codecov
    #        uses: codecov/codecov-action@v3.1.4
    #        with:
    #          env_vars: RUNNER_OS,PYTHON_VERSION
    #          file: ./coverage.xml
    #          fail_ci_if_error: false
    #          name: codecov-umbrella
