name: Latest Changes

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  latest-changes:
    # if required so that the job is only run when the PR is merged
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.LATEST_CHANGES }} # This is a personal access token with the `repo` scope
      - uses: docker://tiangolo/latest-changes:0.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest_changes_file: .github/release-notes.md
          latest_changes_header: '## Latest Changes\n\n'
          debug_logs: true
