name: "Repo usage stats"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  calculate-stats:
    runs-on: ubuntu-22.04
    environment: "analytics"
    steps:
      - uses: jgehrcke/github-repo-stats@HEAD
        with:
          ghtoken: ${{ secrets.GH_TOKEN_ANALYTICS }}
